/** City */
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE [TABLE_NAME] = 'City' AND [COLUMN_NAME] = 'CountryId')
BEGIN
    ALTER TABLE		[dbo].[City]
	ADD CONSTRAINT	FK_City_Country
	FOREIGN KEY		(CountryId) REFERENCES City(Id);
END


/** User */
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE [TABLE_NAME] = 'User' AND [COLUMN_NAME] = 'CityId')
BEGIN
	ALTER TABLE		[dbo].[User]
	ADD CONSTRAINT	FK_User_City
	FOREIGN KEY		(CityId) REFERENCES City(Id);
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE [TABLE_NAME] = 'User' AND [COLUMN_NAME] = 'CountryId')
BEGIN
	ALTER TABLE		[dbo].[User]
	ADD CONSTRAINT	FK_User_Country
	FOREIGN KEY		(CountryId) REFERENCES Country(Id);
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE [TABLE_NAME] = 'User' AND [COLUMN_NAME] = 'CategoryId')
BEGIN
	ALTER TABLE		[dbo].[User]
	ADD CONSTRAINT	FK_User_Category
	FOREIGN KEY		(CategoryId) REFERENCES Category(Id);
END
